apiVersion: v1
kind: pod
metadata:
  name: nginx #nginx is the name of the pod. 
  labels: #labels are key-value pairs that are used to organize and categorize Kubernetes resources. In this case, the pod is labeled with the following key-value pairs:
    project: roboshop
    environment: dev
    purpose: poc
spec: #specification for the pod's desired state
  containers:
    - name: nginx #name of the container within the pod. In this case, the container is named "nginx".
      image: nginx:latest #image specifies the Docker image to be used for the container.
      ports: #ports specify the network ports to expose from the container.
        - containerPort: 80 #containerPort specifies the port number to expose from the container.