apiVersion: v1
kind: Pod
metadata: 
  name: hostpath-test-pod
spec:
  container: 
  - name: app-container
    image: busybox:latest
    commad: ["/bin/sh", "-c", "cat /container-data/host-file.txt; sleep 3600"]
    volumeMount:
    - name: ec2-storage
      mountPath: /container-data
  volumes:
  - name: ec2-storage
    hostPath:
      path: /var/tmp/my-app-data
      type: Directory
