apiVersion: v1
kind: Pod
metadata: 
  name: hostpath-test-pod
spec:
  containers: 
  - name: app-container
    image: busybox:latest
    command: ["/bin/sh", "-c", "cat /container-data/host-file.txt; sleep 3600"]
    volumeMounts:
    - name: ec2-storage
      mountPath: /container-data
  volumes:
  - name: ec2-storage
    hostPath:
      path: /var/tmp/
      type: Directory
